### ISSUE TITLE
how to use this tool ???

### ISSUE THREAD

**Issue by GISerCAU** [Esri/geoprocessing-tools-for-hadoop#10]
1、down the geoprocessing-tools-for-hadoop-master.zip and unzip;
2、add the HadoopTools.pyt to the box;

but all of the tools show a problem: and not to use?

the python error

Traceback (most recent call last):
  File "<string>", line 205, in getParameterInfo
  File "d:\arcgis\arcgisinfo10.2\desktop10.2\arcpy\arcpy\arcobjects\mixins.py", line 286, in __init__
    setattr(self, attrib, attribvalue)
  File "d:\arcgis\arcgisinfo10.2\desktop10.2\arcpy\arcpy\arcobjects\_base.py", line 89, in _set
    return setattr(self._arc_object, attr_name, cval(val))
ValueError: ParameterObject: DataType \u5c5e\u6027\u7684\u8f93\u5165\u503c\u65e0\u6548

**Comment by smambrose** [comment]
Hi @GISerCAU - thanks for your feedback.

Are you able to give a screen shot of the tool box?
Were you able to follow either of these steps? [Method 1](https://github.com/Esri/gis-tools-for-hadoop/wiki/Getting-the-results-of-a-Hive-query-into-ArcGIS) and [Method 2](https://github.com/Esri/gis-tools-for-hadoop/wiki/Getting-a-Feature-Class-into-HDFS)

Lastly, are you using a Hadoop cluster or a VM?
