### ISSUE TITLE
FeaturesToJSON chokes on % in attributes 

### ISSUE THREAD

**Issue by mklaber** [Esri/geoprocessing-tools-for-hadoop#8]
In shapefiles with text attributes that include the percent sign (`%`), [JSONUtil.py](https://github.com/Esri/geoprocessing-tools-for-hadoop/blob/master/JSONUtil.py) fails for both Enclosed and Unenclosed _Features to JSON_ options.

I'd submit a pull request if only I was better at python.

Here are two examples and the resulting errors for both enclosed and unenclosed JSON:

## Example 1

```
secure.firstenergycorp.com/servlet/com.firstenergycorp.webobjects.Engine;jsessionid=NILS2LQAABJWHLA1AAP1LPI?s=com.firstenergycorp.www.Home&o=43304514&q=3&p=%2FContact+Us
```

*Enclosed* output:

```
Executing: FeaturesToJSON iou_terr D:\GIS_DATA\platts\enc_float.json ENCLOSED_JSON FORMATTED
Start Time: Fri Mar 06 11:39:38 2015
Running script FeaturesToJSON...

Traceback (most recent call last):
  File "<string>", line 363, in execute
  File "D:\Code\geoprocessing-tools-for-hadoop\JSONUtil.py", line 368, in ConvertFC2JSON
    geometry_str = unicode(row[len(row) - 1]) if pjson != True else unicode(json.dumps(json.loads(row[len(row) - 1]), indent=4))
TypeError: a float is required

Failed to execute (FeaturesToJSON).
Failed at Fri Mar 06 11:39:39 2015 (Elapsed Time: 0.97 seconds)
```

*Unenclosed* output:

```
Executing: FeaturesToJSON iou_terr D:\GIS_DATA\platts\iou_unenc_some_bad.json UNENCLOSED_JSON FORMATTED
Start Time: Fri Mar 06 11:24:03 2015
Running script FeaturesToJSON...

Traceback (most recent call last):
  File "<string>", line 365, in execute
  File "D:\Code\geoprocessing-tools-for-hadoop\JSONUtil.py", line 422, in ConvertFC2JSONUnenclosed
    attributes_json.clear()
TypeError: a float is required

Failed to execute (FeaturesToJSON).
Failed at Fri Mar 06 11:24:04 2015 (Elapsed Time: 0.93 seconds)
```

## Example 2

```
"www.heco.com/CDA/default/0,1999,TCID%253D8%2526CCID%253D0%2526LCID%253D0%2526CTYP%253DARTC,00.html"
```

*Enclosed* output:

```
Executing: FeaturesToJSON iou_terr D:\GIS_DATA\platts\enc_format_char.json ENCLOSED_JSON FORMATTED
Start Time: Fri Mar 06 11:40:48 2015
Running script FeaturesToJSON...

Traceback (most recent call last):
  File "<string>", line 363, in execute
  File "D:\Code\geoprocessing-tools-for-hadoop\JSONUtil.py", line 368, in ConvertFC2JSON
    geometry_str = unicode(row[len(row) - 1]) if pjson != True else unicode(json.dumps(json.loads(row[len(row) - 1]), indent=4))
ValueError: unsupported format character 'D' (0x44) at index 261

Failed to execute (FeaturesToJSON).
Failed at Fri Mar 06 11:40:52 2015 (Elapsed Time: 3.92 seconds)
```

*Unenclosed* output:

```
Executing: FeaturesToJSON iou_terr D:\GIS_DATA\platts\iou_unenc_some_bad.json UNENCLOSED_JSON FORMATTED
Start Time: Fri Mar 06 11:25:06 2015
Running script FeaturesToJSON...

Traceback (most recent call last):
  File "<string>", line 365, in execute
  File "D:\Code\geoprocessing-tools-for-hadoop\JSONUtil.py", line 422, in ConvertFC2JSONUnenclosed
    attributes_json.clear()
ValueError: unsupported format character 'D' (0x44) at index 261

Failed to execute (FeaturesToJSON).
Failed at Fri Mar 06 11:25:09 2015 (Elapsed Time: 3.88 seconds)
```

## Workaround

I'm just going to null out those attribute values.

**Comment by climbage** [comment]
Interesting.  Can you post a small sample that's failing?  My first guess would be an issue with character encoding.

**Comment by mklaber** [comment]
Yea, I'm sure it's character encoding related to [this bidness](https://docs.python.org/2/library/string.html#formatspec). 

The data set I'm working with is proprietary and I'm not sure I have the time or can remember how to make an arbitrary shapefile. Could you send me an email to  klaber at gmail and I'll send it to you offline?

**Comment by azhigimont** [comment]
I’ll take a look!
Thanks,
Alex.

**Comment by azhigimont** [comment]
I've installed the fix for this issue into JSONUtil.py
